### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Requiao** [rolfjoseph/OpenWebsoccer-2016-PHP-7-#8]
How do I solve this problem?
It occurs when installing. It does not actually install. 
I copied the files into the server, but this error appeared. In "OpenWebSoccer-5.2.3" version ran fine. But this could not.
![sem titulo](https://cloud.githubusercontent.com/assets/22676363/19336496/4789a376-90e2-11e6-8689-109ae2987b00.jpg)

**Comment by rolfjoseph** [comment]
Your provider has a open_basedir restriction, rename the .htaccess file, that can be solve the problem.

Your wrote the OpenWebSoccer-5.2.3 runs fine. You really has set to php7 ? My Version runs only at php7 and on php7 the OpenWebSoccer-5.2.3 can´t run fine, because you can´t login at the admincenter  with php7 !

The differences can you look on these testserver php70.erdemcan.de/2016/ or php70.erdemcan.de/524/

**Comment by Requiao** [comment]
Yes. I use php 7.

I will rename the .htaccess file

thanks!

**Comment by Requiao** [comment]
New error. Please Help.
I use PHP 7.

![sem titulo](https://cloud.githubusercontent.com/assets/22676363/20418647/d8ca27e6-ad36-11e6-9ec1-b661430f769a.jpg)

**Comment by rolfjoseph** [comment]
Why now this problem ?

This is a problem by your webserver, see for solution -> 

http://www.templatemonster.com/help/de/open_basedir-restriction-in-effect-filex-is-not-within-the-allowed-paths-y.html#gref

or

http://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths
