### ISSUE TITLE
Error. Job execution.

### ISSUE THREAD

**Issue by Requiao** [rolfjoseph/OpenWebsoccer-2016-PHP-7-#9]
Error. Execute jobs. Please help!

Fatal error: Uncaught exception 'Exception' with message 'Database Query Error: MySQL server has gone away' in /home/u384192891/public_html/classes/DbConnection.class.php:286 Stack trace: #0 /home/u384192891/public_html/classes/DbConnection.class.php(91): DbConnection->executeQuery('SELECT expires,...') #1 /home/u384192891/public_html/classes/DbSessionManager.class.php(93): DbConnection->querySelect('expires, sessio...', '_session', 'session_id = '%...', 'ee166fa2406786c...') #2 /home/u384192891/public_html/classes/DbSessionManager.class.php(129): DbSessionManager->read('ee166fa2406786c...') #3 [internal function]: DbSessionManager->write('ee166fa2406786c...', 'valid|i:1;useri...') #4 [internal function]: session_write_close() #5 {main} thrown in /home/u384192891/public_html/classes/DbConnection.class.php on line 286

**Comment by rolfjoseph** [comment]
At first, you have to discribe as follows, to tell you a given problem a the future to the right websoccer version, not here and there the same error to place.

This is a typical misplaced issue. The Error comes inside with the message "MySQL server has gone away". This isn´t a Websoccer error !!!

With a litte look at google, can you saw, that the Problem is the MySQL-Server. To resolve this Problem is here one of the founded links -> http://piwik.org/faq/troubleshooting/faq_183/

Ingo Hofmann does not support his version until round a bout 18 months.

# **And i dont´t support this outdated version !!!**
